[package]
name = "usb-looper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9.4"
slint = "1.7.2"

[build-dependencies]
slint-build = "1.7.2"
